/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsultancyRouteImport } from './routes/consultancy'
import { Route as KundaliRouteImport } from './routes/kundali'
import { Route as SamagriRouteImport } from './routes/samagri'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyRoute = ConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const KundaliRoute = KundaliRouteImport.update({
  id: '/kundali',
  path: '/kundali',
  getParentRoute: () => rootRouteImport,
} as any)
const SamagriRoute = SamagriRouteImport.update({
  id: '/samagri',
  path: '/samagri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/kundali': typeof KundaliRoute
  '/samagri': typeof SamagriRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/kundali': typeof KundaliRoute
  '/samagri': typeof SamagriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/kundali': typeof KundaliRoute
  '/samagri': typeof SamagriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/consultancy' | '/kundali' | '/samagri'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/consultancy' | '/kundali' | '/samagri'
  id: '__root__' | '/' | '/about' | '/consultancy' | '/kundali' | '/samagri'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultancyRoute: typeof ConsultancyRoute
  KundaliRoute: typeof KundaliRoute
  SamagriRoute: typeof SamagriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy': {
      id: '/consultancy'
      path: '/consultancy'
      fullPath: '/consultancy'
      preLoaderRoute: typeof ConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundali': {
      id: '/kundali'
      path: '/kundali'
      fullPath: '/kundali'
      preLoaderRoute: typeof KundaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samagri': {
      id: '/samagri'
      path: '/samagri'
      fullPath: '/samagri'
      preLoaderRoute: typeof SamagriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultancyRoute: ConsultancyRoute,
  KundaliRoute: KundaliRoute,
  SamagriRoute: SamagriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
